<font size="10">Exercise 1</font>

In [4]:
import pandas as pd


data = {
    "Title": [
        "Harry Potter and the Philosopher's Stone",
        "The Hobbit",
        "1984",
        "Pride and Prejudice",
        "The Great Gatsby",
        "To Kill a Mockingbird"
    ],
    "Author": [
        "J.K. Rowling",
        "J.R.R. Tolkien",
        "George Orwell",
        "Jane Austen",
        "F. Scott Fitzgerald",
        "Harper Lee"
    ],
    "Year of publication": [
        1997, 1937, 1949, 1813, 2025, 2016
    ],
    "Price": [
        15.99, 12.50, 10.99, 9.50, 11.25, 13.75
    ]
}

df = pd.DataFrame(data)

df

,Title,Author,Year of publication,Price
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99
1,The Hobbit,J.R.R. Tolkien,1937,12.50
2,1984,George Orwell,1949,10.99
3,Pride and Prejudice,Jane Austen,1813,9.50
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
5,To Kill a Mockingbird,Harper Lee,2016,13.75

In [5]:
average_price = df['Price'].mean()
average_price

np.float64(12.33)

In [6]:
BooksAfter2015 = df[df['Year of publication'] > 2015]
BooksAfter2015

                   Title               Author  Year of publication  Price
4       The Great Gatsby  F. Scott Fitzgerald                 2025  11.25
5  To Kill a Mockingbird           Harper Lee                 2016  13.75

In [7]:
sortedDf = df.sort_values(by='Price')
sortedDf

,Title,Author,Year of publication,Price
3,Pride and Prejudice,Jane Austen,1813,9.50
2,1984,George Orwell,1949,10.99
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
1,The Hobbit,J.R.R. Tolkien,1937,12.50
5,To Kill a Mockingbird,Harper Lee,2016,13.75
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99

<font size="10">Exercise 2</font>

In [8]:
df1 = pd.read_csv("Orders.csv")
df1

    Order number           Customer       Date   Price
0           1001         John Smith   1/1/2026   25.99
1           1002       Emma Johnson   1/2/2026   43.34
2           1003      Michael Brown   1/3/2026   60.69
3           1004       Olivia Davis   1/4/2026   78.04
4           1005       James Wilson   1/5/2026   95.39
5           1006      Sophia Miller   1/6/2026  112.74
6           1007     William Taylor   1/7/2026  130.09
7           1008  Isabella Anderson   1/8/2026  147.44
8           1009    Benjamin Thomas   1/9/2026  164.79
9           1010        Mia Jackson  1/10/2026  182.14
10          1011         John Smith  1/11/2026  199.49
11          1012       Emma Johnson  1/12/2026  216.84
12          1013      Michael Brown  1/13/2026  234.19
13          1014       Olivia Davis  1/14/2026  251.54
14          1015       James Wilson  1/15/2026   18.89
15          1016      Sophia Miller  1/16/2026   36.24
16          1017     William Taylor  1/17/2026   53.59
17          1018  Isabella Anderson  1/18/2026   70.94
18          1019    Benjamin Thomas  1/19/2026   88.29
19          1020        Mia Jackson  1/20/2026  105.64
20          1021         John Smith  1/21/2026  122.99
21          1022       Emma Johnson  1/22/2026  140.34
22          1023      Michael Brown  1/23/2026  157.69
23          1024       Olivia Davis  1/24/2026  175.04
24          1025       James Wilson  1/25/2026  192.39
25          1026      Sophia Miller  1/26/2026  209.74
26          1027     William Taylor  1/27/2026  227.09
27          1028  Isabella Anderson  1/28/2026  244.44
28          1029    Benjamin Thomas  1/29/2026  261.79
29          1030        Mia Jackson  1/30/2026   29.14
30          1031         John Smith  1/31/2026   46.49
31          1032       Emma Johnson   2/1/2026   63.84
32          1033      Michael Brown   2/2/2026   81.19
33          1034       Olivia Davis   2/3/2026   98.54
34          1035       James Wilson   2/4/2026  115.89
35          1036      Sophia Miller   2/5/2026  133.24
36          1037     William Taylor   2/6/2026  150.59
37          1038  Isabella Anderson   2/7/2026  167.94
38          1039    Benjamin Thomas   2/8/2026  185.29
39          1040        Mia Jackson   2/9/2026  202.64
40          1041         John Smith  2/10/2026  219.99
41          1042       Emma Johnson  2/11/2026  237.34
42          1043      Michael Brown  2/12/2026  254.69
43          1044       Olivia Davis  2/13/2026   22.04
44          1045       James Wilson  2/14/2026   39.39
45          1046      Sophia Miller  2/15/2026   56.74
46          1047     William Taylor  2/16/2026   74.09
47          1048  Isabella Anderson  2/17/2026   91.44
48          1049    Benjamin Thomas  2/18/2026  108.79
49          1050        Mia Jackson  2/19/2026  126.14

In [9]:
df1.head(10)

   Order number           Customer       Date   Price
0          1001         John Smith   1/1/2026   25.99
1          1002       Emma Johnson   1/2/2026   43.34
2          1003      Michael Brown   1/3/2026   60.69
3          1004       Olivia Davis   1/4/2026   78.04
4          1005       James Wilson   1/5/2026   95.39
5          1006      Sophia Miller   1/6/2026  112.74
6          1007     William Taylor   1/7/2026  130.09
7          1008  Isabella Anderson   1/8/2026  147.44
8          1009    Benjamin Thomas   1/9/2026  164.79
9          1010        Mia Jackson  1/10/2026  182.14

In [10]:
counts = df1['Customer'].value_counts()
repeated_names = counts[counts > 1]
repeated_names

Customer
John Smith           5
Emma Johnson         5
Michael Brown        5
Olivia Davis         5
James Wilson         5
Sophia Miller        5
William Taylor       5
Isabella Anderson    5
Benjamin Thomas      5
Mia Jackson          5
Name: count, dtype: int64

In [11]:
max_price = df1['Price'].max()

min_price = df1['Price'].min()

max_price, min_price

(np.float64(261.79), np.float64(18.89))

In [12]:
total_price = df1['Price'].sum()

total_price

np.float64(6553.250000000001)

In [13]:

data1 = {
    "Product": [
        "Chicken Breast", "Egg", "Banana", "Apple", "Salmon",
        "White Rice", "Greek Yogurt", "Almonds", "Broccoli", "Lentils"
    ],
    "Category": [
        "Meat", "Dairy & Eggs", "Fruit", "Fruit", "Fish",
        "Grains", "Dairy", "Nuts", "Vegetables", "Legumes"
    ],
    "Calories": [165, 155, 89, 52, 208, 130, 97, 579, 34, 116],
    "Proteins": [31.0, 13.0, 1.1, 0.3, 20.4, 2.7, 9.0, 21.2, 2.8, 9.0]
}

df2 = pd.DataFrame(data1)

df2

          Product      Category  Calories  Proteins
0  Chicken Breast          Meat       165      31.0
1             Egg  Dairy & Eggs       155      13.0
2          Banana         Fruit        89       1.1
3           Apple         Fruit        52       0.3
4          Salmon          Fish       208      20.4
5      White Rice        Grains       130       2.7
6    Greek Yogurt         Dairy        97       9.0
7         Almonds          Nuts       579      21.2
8        Broccoli    Vegetables        34       2.8
9         Lentils       Legumes       116       9.0

In [14]:
calories300plus = df2[df2['Calories'] > 300]

calories300plus

   Product Category  Calories  Proteins
7  Almonds     Nuts       579      21.2

In [15]:
average_protein = df2.groupby('Category')['Proteins'].mean()
average_protein

Category
Dairy            9.0
Dairy & Eggs    13.0
Fish            20.4
Fruit            0.7
Grains           2.7
Legumes          9.0
Meat            31.0
Nuts            21.2
Vegetables       2.8
Name: Proteins, dtype: float64

In [17]:
sortedDf2 = df2.sort_values(by='Calories', ascending=False)
sortedDf2

          Product      Category  Calories  Proteins
7         Almonds          Nuts       579      21.2
4          Salmon          Fish       208      20.4
0  Chicken Breast          Meat       165      31.0
1             Egg  Dairy & Eggs       155      13.0
5      White Rice        Grains       130       2.7
9         Lentils       Legumes       116       9.0
6    Greek Yogurt         Dairy        97       9.0
2          Banana         Fruit        89       1.1
3           Apple         Fruit        52       0.3
8        Broccoli    Vegetables        34       2.8

<font size="10">Exercise 4</font>

In [18]:
import pandas as pd

data2 = {
    "Name": [
        "John Smith", "Emma Johnson", "Michael Brown",
        "Sophia Davis", "James Wilson", "Olivia Taylor",
        "William Anderson", "Ava Thomas", "Daniel Martinez",
        "Isabella Garcia"
    ],
    "Project": [
        "Website Development", "Mobile App", "Data Analysis",
        "Marketing Campaign", "Database Design",
        "Website Development", "Mobile App", "Data Analysis",
        "Marketing Campaign", "Database Design"
    ],
    "Hours": [8, 6, 7, 5, 9, 4, 8, 6, 7, 5]
}

df3 = pd.DataFrame(data2)
df3

               Name              Project  Hours
0        John Smith  Website Development      8
1      Emma Johnson           Mobile App      6
2     Michael Brown        Data Analysis      7
3      Sophia Davis   Marketing Campaign      5
4      James Wilson      Database Design      9
5     Olivia Taylor  Website Development      4
6  William Anderson           Mobile App      8
7        Ava Thomas        Data Analysis      6
8   Daniel Martinez   Marketing Campaign      7
9   Isabella Garcia      Database Design      5

In [20]:
overallHours = df3.groupby('Name')['Hours'].sum()
overallHours

Name
Ava Thomas          6
Daniel Martinez     7
Emma Johnson        6
Isabella Garcia     5
James Wilson        9
John Smith          8
Michael Brown       7
Olivia Taylor       4
Sophia Davis        5
William Anderson    8
Name: Hours, dtype: int64

In [21]:
overallHours1 = df3.groupby('Project')['Hours'].sum()
overallHours1

Project
Data Analysis          13
Database Design        14
Marketing Campaign     12
Mobile App             14
Website Development    12
Name: Hours, dtype: int64

In [26]:
maxHours = df3.loc[df3["Hours"].idxmax(), "Name"]
maxHours

'James Wilson'

<font size="10">Exercise 5</font>

In [27]:
import pandas as pd

data3 = {
    "Movie": [
        "Avatar", "Titanic", "Inception", "The Dark Knight",
        "Interstellar", "Avengers: Endgame", "Joker", "Frozen",
        "Spider-Man: No Way Home", "The Lion King", "Oppenheimer",
        "Barbie", "Dune: Part Two", "Jurassic World", "The Batman",
        "Toy Story 4", "Doctor Strange", "Black Panther",
        "Finding Nemo", "Mission: Impossible"
    ],
    "City": [
        "Baku", "London", "New York", "Paris", "Tokyo",
        "Baku", "Berlin", "Madrid", "Rome", "London",
        "New York", "Paris", "Tokyo", "Berlin", "Madrid",
        "Rome", "Baku", "London", "Paris", "New York"
    ],
    "Sold tickets": [
        1250, 980, 1450, 1120, 1380,
        2100, 870, 950, 1670, 1050,
        1320, 1540, 1180, 920, 1090,
        840, 1430, 1270, 760, 1160
    ]
}

df4 = pd.DataFrame(data3)
df4

                      Movie      City  Sold tickets
0                    Avatar      Baku          1250
1                   Titanic    London           980
2                 Inception  New York          1450
3           The Dark Knight     Paris          1120
4              Interstellar     Tokyo          1380
5         Avengers: Endgame      Baku          2100
6                     Joker    Berlin           870
7                    Frozen    Madrid           950
8   Spider-Man: No Way Home      Rome          1670
9             The Lion King    London          1050
10              Oppenheimer  New York          1320
11                   Barbie     Paris          1540
12           Dune: Part Two     Tokyo          1180
13           Jurassic World    Berlin           920
14               The Batman    Madrid          1090
15              Toy Story 4      Rome           840
16           Doctor Strange      Baku          1430
17            Black Panther    London          1270
18             Finding Nemo     Paris           760
19      Mission: Impossible  New York          1160

In [28]:
overallHours2 = df4.groupby('Movie')['Sold tickets'].sum()
overallHours2

Movie
Avatar                     1250
Avengers: Endgame          2100
Barbie                     1540
Black Panther              1270
Doctor Strange             1430
Dune: Part Two             1180
Finding Nemo                760
Frozen                      950
Inception                  1450
Interstellar               1380
Joker                       870
Jurassic World              920
Mission: Impossible        1160
Oppenheimer                1320
Spider-Man: No Way Home    1670
The Batman                 1090
The Dark Knight            1120
The Lion King              1050
Titanic                     980
Toy Story 4                 840
Name: Sold tickets, dtype: int64

In [29]:
overallHours3 = df4.groupby('City')['Sold tickets'].sum()
overallHours3

City
Baku        4780
Berlin      1790
London      3300
Madrid      2040
New York    3930
Paris       3420
Rome        2510
Tokyo       2560
Name: Sold tickets, dtype: int64

In [30]:
maxMovie = df4.loc[df4["Sold tickets"].idxmax(), "Movie"]
maxMovie

'Avengers: Endgame'