In [1]:
import pandas as pd


data = {
    "Title": [
        "Harry Potter and the Philosopher's Stone",
        "The Hobbit",
        "1984",
        "Pride and Prejudice",
        "The Great Gatsby",
        "To Kill a Mockingbird"
    ],
    "Author": [
        "J.K. Rowling",
        "J.R.R. Tolkien",
        "George Orwell",
        "Jane Austen",
        "F. Scott Fitzgerald",
        "Harper Lee"
    ],
    "Year of publication": [
        1997, 1937, 1949, 1813, 2025, 2016
    ],
    "Price": [
        15.99, 12.50, 10.99, 9.50, 11.25, 13.75
    ]
}

df = pd.DataFrame(data)

df

,Title,Author,Year of publication,Price
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99
1,The Hobbit,J.R.R. Tolkien,1937,12.50
2,1984,George Orwell,1949,10.99
3,Pride and Prejudice,Jane Austen,1813,9.50
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
5,To Kill a Mockingbird,Harper Lee,2016,13.75

In [5]:
average_price = df['Price'].mean()
average_price

np.float64(12.33)

In [2]:
BooksAfter2015 = df[df['Year of publication'] > 2015]
BooksAfter2015

                   Title               Author  Year of publication  Price
4       The Great Gatsby  F. Scott Fitzgerald                 2025  11.25
5  To Kill a Mockingbird           Harper Lee                 2016  13.75

In [3]:
sortedDf = df.sort_values(by='Price')
sortedDf

,Title,Author,Year of publication,Price
3,Pride and Prejudice,Jane Austen,1813,9.50
2,1984,George Orwell,1949,10.99
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
1,The Hobbit,J.R.R. Tolkien,1937,12.50
5,To Kill a Mockingbird,Harper Lee,2016,13.75
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99